### ISSUE TITLE
smoothsurf works incorrectly

### ISSUE THREAD

**Issue by StudentFS2** [fangq/iso2mesh#53] opened 2021-01-22 13:13 UTC
Hi!
smoothsurf clearly work incorrectly on my geometry. I attach geometry here
[files.zip](https://github.com/fangq/iso2mesh/files/5856027/files.zip)
load('el.mat')
load('no.mat')
plotmesh(no,el)
sz=size(no);
no=smoothsurf(no,[],meshconn(el,sz(1)),1);
plotmesh(no,el)
clearly puts something inside of one of the channels.
Best regards

**Comment by fangq** [comment] 2021-06-06 19:06
@StudentFS2, again, sorry for not reading about this report until now.

I loaded your data, it looks like the garbled nodes/elements are there already before smoothsurf. 

the presence of these garbled nodes is caused by a upstream CGAL bug I explained in #54 - the meshing process failed to complete before reaching the maximum node limit (type `length(no)`, you can see it is 40,000, which is the default maximum node limit of vol2surf.)

because of this, I am closing this ticket because `smoothsurf` works as expected. it was `vol2surf` (specifically, [cgalsurf](https://github.com/fangq/iso2mesh/blob/master/tools/cgalsurf/mesh_a_3d_gray_image.cpp)) that failed to create a valid mesh.

**Closed by fangq** 2021-06-06 19:06 UTC
