### ISSUE TITLE
The work of the meshing algorithm is ustable for big meshes

### ISSUE THREAD

**Issue by StudentFS2** [fangq/iso2mesh#54] opened 2021-01-24 15:06 UTC
Hi!
Meshing with 
[node,elem,face]=v2m(part,0.5,3,50);
or
[no,el,regions,holes]=v2s(part,0.5,3);
works fine for small volumes (100x100x100 voxels):
![Capture1](https://user-images.githubusercontent.com/77841106/105634231-195ef880-5e6e-11eb-8821-276bba5fc367.JPG)
but for bigger volumes (500x100x500 voxels) the real surfaces are no longer followed by the exactly same command
![Capture2](https://user-images.githubusercontent.com/77841106/105634320-79559f00-5e6e-11eb-8969-cc66d0446e88.JPG)
![Capture3](https://user-images.githubusercontent.com/77841106/105634355-ad30c480-5e6e-11eb-89b9-e52304be16a2.JPG)

**Comment by StudentFS2** [comment] 2021-01-24 15:09
Here is the geometry
[part.zip](https://github.com/fangq/iso2mesh/files/5862497/part.zip)

**Comment by fangq** [comment] 2021-06-06 19:01
sorry @StudentFS2 for the delay - for some reason, I did not get notification for this issue, until going over these today.

This is a known issue related to CGAL, see Issue #3, particularly, this infinite loop bug I reported 11 years ago

http://cgal-discuss.949826.n4.nabble.com/Bug-infinite-refinement-for-CGAL-Surface-mesher-td3024338.html

When you run your v2m command with a large volume, the printed message actually contains a warning:
```
>> [node,elem,face]=v2m(part,0.3,3,50);
extracting surfaces from a volume ...
region 1 centroid :	50.000000 1.666667 1.333333

processing threshold level 1...
Surface Mesh Extraction Utility (Based on CGAL 3.8)
(modified for iso2mesh by Qianqian Fang)
http://iso2mesh.sf.net

RNG seed 1648335518
set initial mesh size to 50
Refining... maximum node number is set to 40000
**reach maximum node limit, element angular bound may not satisfied**

done.
Final number of points: 40000
surface mesh generation is complete
generating tetrahedral mesh from closed surfaces ...
creating volumetric mesh from a surface mesh ...
volume mesh generation is complete
```

see in the middle, **reach maximum node limit, element angular bound may not satisfied**

what that means is that CGAL surface extraction function fails to complete the mesh extraction before the maximum node limit set in the program (40,000 by default). that means the mesh output is incomplete.

the reason that 40,000 node is not enough to create the surface is not because the surface is extremely dense, but CGAL is trapped in a "non-manifold" shape and produces extremely dense node cluster (and fails to stop), see reply from CGAL developer

http://cgal-discuss.949826.n4.nabble.com/Bug-infinite-refinement-for-CGAL-Surface-mesher-tp3024338p3025666.html


unfortunately, I set the threshold to a different value than 0.5, as well as increase the maximum node limit via [opt.maxnode](https://github.com/fangq/iso2mesh/blob/master/vol2surf.m#L27), CGAL still won't  be able to complete the mesh extraction.

because this is an upstream (CGAL) bug, so I am closing this ticket and use #3 to track the upstream fix.

**Closed by fangq** 2021-06-06 19:01 UTC

**Comment by lrineau** [comment] 2021-06-07 08:48
Hi @fangq, @StudentFS2. I am a CGAL develop, and actually in charge of the 3D Mesh Generation in CGAL. And I am the CGAL develop you were discussing with on Nabble.

As I have already said in the past (ten years ago), I am still willing to help. The issue is to be able to reproduce the issue using a pure C++ code, because I cannot use MathLab.
